### ISSUE TITLE
Add a page 2 explaining deliverables

### ISSUE THREAD

**Issue by julienjamme** [julienjamme/handbook_sdc_from_doc_to_md#128]

**Comment by ppdewolf** [comment]
I could also just produce a coverpage as pdf. And then just add that page to the deliverable I will send to Eurostat. Then we do not have to change anything in the qmd files, as it is only for the deliverable-version within the project. (I guess this is what you are referring to)

**Comment by julienjamme** [comment]
In fact, I've added a page to the pdf version just after the cover page. I adapted the text written for the geo guidelines. None of the qmd files are modified. It is managed in the "_titlepage.tex" file.
Hence, this text is not mentionned in the html version.
Let me know if it is ok.

The pdf is downloadable here: https://github.com/julienjamme/handbook_sdc_from_doc_to_md/blob/gh-pages/Handbook-on-Statistical-Disclosure-Control.pdf

**Comment by ppdewolf** [comment]
I thought you were referring to something else ;-) 
We also discussed an additional "coverpage" needed for submitting the deliverable (see also the very first page of the Geo-guidelines or the Census guidelines). I propose that I will take care of that when I send it to Eurostat/Bulgaria by just adding a pdf of the cover page to the overall handbook-pdf.

**Comment by julienjamme** [comment]
We can copy paste and adapt the title page of the geoguidelines within the _titlepage.tex file. Not so difficult actually.

As nobody reacted when I asked if the title page is ok, I believed it was fine. In fact, I didn't understand that the cover page + the title page are two different pages.
Sorry to have misunderstood.

**Comment by ppdewolf** [comment]
No problem, I misunderstood your first issue as well ;-)

As discussed with Aleksandra, the additional coverpage is only needed for submitting the deliverable to the Eurostat system. It should not appear in the generally available pdf-version. That's why I suggested that I will just add something like  the attached pdf-page (might still change a bit) to the handbook-pdf and not include it in the sources on github. It's only for administrative purposes within the project.
[NewCoverPageHandbook-1.pdf](https://github.com/user-attachments/files/16609002/NewCoverPageHandbook-1.pdf)

**Comment by julienjamme** [comment]
ok let's do like this !
